# Generated by Django 4.0.2 on 2023-01-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_comment_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='stars',
            field=models.CharField(choices=[('1', 'VeryBad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'VeryGood')], max_length=10),
        ),
    ]
